<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../CubleyDiseqc.Managed/DiseqcCommandBuilder.cs" Link="Managed/DiseqcCommandBuilder.cs" />
    <Compile Include="../../CubleyDiseqc.Managed/DiseqcGotoAngleEncoder.cs" Link="Managed/DiseqcGotoAngleEncoder.cs" />
    <Compile Include="../../CubleyDiseqc.Managed/DiseqcPositionEstimate.cs" Link="Managed/DiseqcPositionEstimate.cs" />
    <Compile Include="../../CubleyDiseqc.Managed/DiseqcProtocol.cs" Link="Managed/DiseqcProtocol.cs" />
    <Compile Include="../../CubleyControl/ApplicationConfigurationRecord.cs" Link="Control/ApplicationConfigurationRecord.cs" />
    <Compile Include="../../CubleyControl/ApplicationConfiguration.cs" Link="Control/ApplicationConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" PrivateAssets="all" />
  </ItemGroup>
</Project>